# Ballerina demo config file
    consumerKey = "DzPyBp1ucDA1tiRBiGdRbfyqg"
    consumerSecret = "UkXwGYcRrCqhhwghKbht87nmvZX4kyn15b9bjM7GXDuE2WK8dt"
    accessToken = "443843085-1miFt5YuIUsEOj5gO34zcXl4mmcaQIVkW5OrkidL"
    accessTokenSecret = "r03F15Lw1r7VJ7gJk290pW0s53RymmKboAEAVTgnb2tYP"
